# Puzzle 1: Calculate program output

### both wires start at the same port; find closest intersection due to the manhattan distance

In [ ]:
import numpy as np

## Load input

In [ ]:
with open('./input3.txt', 'r') as file:

    data = file.readlines()

In [3]:
wire1 = data[0].split(',')
wire2 = data[1].split(',')

#### Create an example grid

In [94]:
testgrid = np.zeros((5, 5))

In [95]:
testgrid

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [96]:
testgrid[3][2:5] += 1

In [97]:
testgrid

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

In [98]:
testgrid[3][4] = 1

In [100]:
testgrid.T[4][2:5]

array([0., 1., 0.])

#### Create the real grid

In [174]:
grid = np.zeros((24000, 24000))

#### Draw wire 1

In [175]:
wire1[0]

'R1009'

In [176]:
x = 12000
y = 12000

grid[y][x] = 1  # initialization of starting point

for i in wire1:
    if i[0] is 'R':  # steps to the right
        step = int(i[1:])
        grid[y][x+1:x+step+1] += 1
        x += step
    if i[0] is 'L':  # steps to the left
        step = int(i[1:])
        grid[y][x-step:x] += 1
        x -= step
    if i[0] is 'U':  # steps up
        step = int(i[1:])
        grid.T[x][y-step:y] += 1
        y -= step
    if i[0] is 'D':  # steps down
        step = int(i[1:])
        grid.T[x][y+1:y+step+1] += 1
        y += step

#### Draw wire 2

In [177]:
x = 12000
y = 12000

for i in wire2:
    if i[0] is 'R':  # steps to the right
        step = int(i[1:])
        grid[y][x+1:x+step+1] += 1
        x += step
    if i[0] is 'L':  # steps to the left
        step = int(i[1:])
        grid[y][x-step:x] += 1
        x -= step
    if i[0] is 'U':  # steps up
        step = int(i[1:])
        grid.T[x][y-step:y] += 1
        y -= step
    if i[0] is 'D':  # steps down
        step = int(i[1:])
        grid.T[x][y+1:y+step+1] += 1
        y += step

#### find intersections (visitscount > 1)

In [178]:
positions = np.argwhere(grid > 1) 

#### find the closest intersection to starting point 12000, 12000

In [179]:
closest = np.min(np.sum(abs(positions - 12000), axis=1))

In [180]:
print('The Manhattan distance to the closest intersection is {0}.'.format(closest))

The Manhattan distance to the closest intersection is 225.


# Puzzle 2: Search intersection with fewest combined steps

#### Walk along wire 1 and find the distance to any intersection

In [394]:
interdict1 = dict()
for i in positions:
    interdict1['{0}, {1}'.format(i[0], i[1])] = 0  # dict for any intersection of wire 1

In [416]:
x = 12000
y = 12000

stepcount = 0  # initialize stepcounter

for i in wire1:
    if i[0] is 'R':  # steps to the right
        step = int(i[1:])        
        for j in np.where(grid[y][x+1:x+step+1] > 1)[0]:
            if interdict1['{0}, {1}'.format(y, x+j+1)] == 0:
                interdict1['{0}, {1}'.format(y, x+j+1)] += (stepcount + j + 1)
        x += step
        stepcount += step
    if i[0] is 'L':  # steps to the left
        step = int(i[1:])
        for j in np.where(grid[y][x-step:x+1] > 1)[0]:
            if interdict1['{0}, {1}'.format(y, x-(step-j))] == 0:
                interdict1['{0}, {1}'.format(y, x-(step-j))] += (stepcount + (step-j))
        x -= step
        stepcount += step
    if i[0] is 'U':  # steps up
        step = int(i[1:])
        for j in np.where(grid.T[x][y-step:y+1] > 1)[0]:
            if interdict1['{0}, {1}'.format(y-(step-j), x)] == 0:
                interdict1['{0}, {1}'.format(y-(step-j), x)] += (stepcount + (step-j))             
        y -= step
        stepcount += step
    if i[0] is 'D':  # steps down
        step = int(i[1:])
        for j in np.where(grid.T[x][y+1:y+step+1] > 1)[0]:
            if interdict1['{0}, {1}'.format(y+j+1, x)] == 0:
                interdict1['{0}, {1}'.format(y+j+1, x)] += (stepcount + j+1)
        y += step
        stepcount += step

#### Walk along wire 2 and find the distance to any intersection

In [396]:
interdict2 = dict()
for i in positions:
    interdict2['{0}, {1}'.format(i[0], i[1])] = 0  # dict for any intersection of wire 2

In [411]:
x = 12000
y = 12000

stepcount = 0  # initialize stepcounter

for i in wire2:
    if i[0] is 'R':  # steps to the right
        step = int(i[1:])        
        for j in np.where(grid[y][x+1:x+step+1] > 1)[0]:
            if interdict2['{0}, {1}'.format(y, x+j+1)] == 0:
                interdict2['{0}, {1}'.format(y, x+j+1)] += (stepcount + j + 1)
        x += step
        stepcount += step
    if i[0] is 'L':  # steps to the left
        step = int(i[1:])
        for j in np.where(grid[y][x-step:x+1] > 1)[0]:
            if interdict2['{0}, {1}'.format(y, x-(step-j))] == 0:
                interdict2['{0}, {1}'.format(y, x-(step-j))] += (stepcount + (step-j))
        x -= step
        stepcount += step
    if i[0] is 'U':  # steps up
        step = int(i[1:])
        for j in np.where(grid.T[x][y-step:y+1] > 1)[0]:
            if interdict2['{0}, {1}'.format(y-(step-j), x)] == 0:
                interdict2['{0}, {1}'.format(y-(step-j), x)] += (stepcount + (step-j))             
        y -= step
        stepcount += step
    if i[0] is 'D':  # steps down
        step = int(i[1:])
        for j in np.where(grid.T[x][y+1:y+step+1] > 1)[0]:
            if interdict2['{0}, {1}'.format(y+j+1, x)] == 0:
                interdict2['{0}, {1}'.format(y+j+1, x)] += (stepcount + j+1)
        y += step
        stepcount += step

In [414]:
solution = 99999999999
for i in positions:
    if interdict1['{0}, {1}'.format(i[0], i[1])] > 0 and interdict2['{0}, {1}'.format(i[0], i[1])] > 0:
        temp1 = interdict1['{0}, {1}'.format(i[0], i[1])] + interdict2['{0}, {1}'.format(i[0], i[1])]
        if temp1 < solution:
            solution = temp1

In [415]:
print('The solution is {0}.'.format(solution))

The solution is 35194.
